# Generated by Django 6.0.1 on 2026-01-29 19:01

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GigCreation',
            fields=[
                ('id', models.CharField(default=pages.models.generate_firebase_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gig_city', models.CharField(blank=True, max_length=100, null=True)),
                ('gig_state', models.CharField(blank=True, max_length=100, null=True)),
                ('gig_country', models.CharField(blank=True, max_length=100, null=True)),
                ('kreyate_city', models.CharField(blank=True, max_length=100, null=True)),
                ('kreyate_state', models.CharField(blank=True, max_length=100, null=True)),
                ('kreyate_country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('deadline', models.DateField()),
                ('time', models.TimeField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('gig_category', models.CharField(max_length=100)),
                ('gig_review', models.TextField(blank=True, null=True)),
                ('gig_comment', models.TextField(blank=True, null=True)),
                ('gig_kreyate_id', models.IntegerField()),
                ('gig_kreyate_name', models.CharField(max_length=255)),
                ('gig_kreyate_review', models.TextField(blank=True, null=True)),
                ('kreyate_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gig_kreyate_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('method_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('kreyate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('offers', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
