# Generated by Django 6.0.1 on 2026-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigcreation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
