# Generated by Django 6.0.1 on 2026-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_gigcreation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigcreation',
            name='gig_kreyate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
